name: utils

on:
  push:
    branches: [ master, dev ]
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches: [ master, dev ]
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  call-base-test-workflow:
    uses: ./.github/workflows/base_test_workflow.yml
    with:
      module-to-test: utils